# Generated by Django 3.2.16 on 2024-07-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'default_related_name': 'user', 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
