# Generated by Django 3.2.16 on 2024-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoppingcart_user_product_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Количество'),
        ),
    ]
